package br.com.cinejov.views;

import br.com.cinejov.DAOs.IngressoDAO;
import br.com.cinejov.entities.Cliente;
import br.com.cinejov.entities.Filme;
import br.com.cinejov.entities.Ingresso;
import br.com.cinejov.entities.Sessao;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Otavio
 */
public class CompraIngresso extends javax.swing.JFrame {

    /**
     * Creates new form Ingresso
     */
    public CompraIngresso() throws SQLException {
        initComponents();
        this.preencherCampo();
        this.recuperarIngressosVendidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        box11 = new javax.swing.JCheckBox();
        box12 = new javax.swing.JCheckBox();
        box13 = new javax.swing.JCheckBox();
        box14 = new javax.swing.JCheckBox();
        box15 = new javax.swing.JCheckBox();
        box16 = new javax.swing.JCheckBox();
        box21 = new javax.swing.JCheckBox();
        box6 = new javax.swing.JCheckBox();
        box1 = new javax.swing.JCheckBox();
        box17 = new javax.swing.JCheckBox();
        box22 = new javax.swing.JCheckBox();
        box7 = new javax.swing.JCheckBox();
        box2 = new javax.swing.JCheckBox();
        box18 = new javax.swing.JCheckBox();
        box23 = new javax.swing.JCheckBox();
        box8 = new javax.swing.JCheckBox();
        box3 = new javax.swing.JCheckBox();
        box19 = new javax.swing.JCheckBox();
        box24 = new javax.swing.JCheckBox();
        box9 = new javax.swing.JCheckBox();
        box4 = new javax.swing.JCheckBox();
        box20 = new javax.swing.JCheckBox();
        box25 = new javax.swing.JCheckBox();
        box10 = new javax.swing.JCheckBox();
        box5 = new javax.swing.JCheckBox();
        box26 = new javax.swing.JCheckBox();
        box27 = new javax.swing.JCheckBox();
        box28 = new javax.swing.JCheckBox();
        box29 = new javax.swing.JCheckBox();
        box30 = new javax.swing.JCheckBox();
        btnFinalizarCompra = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txthorario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Telão");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        box11.setBackground(new java.awt.Color(51, 255, 51));
        box11.setText("11");
        box11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box12.setBackground(new java.awt.Color(51, 255, 51));
        box12.setText("12");
        box12.setToolTipText("");
        box12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box13.setBackground(new java.awt.Color(51, 255, 51));
        box13.setText("13");
        box13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box14.setBackground(new java.awt.Color(51, 255, 51));
        box14.setText("14");
        box14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box15.setBackground(new java.awt.Color(51, 255, 51));
        box15.setText("15");
        box15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box16.setBackground(new java.awt.Color(51, 255, 51));
        box16.setText("16");
        box16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box21.setBackground(new java.awt.Color(51, 255, 51));
        box21.setText("21");
        box21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box6.setBackground(new java.awt.Color(51, 255, 51));
        box6.setText("6");
        box6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box1.setBackground(new java.awt.Color(51, 255, 51));
        box1.setText("1");
        box1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });

        box17.setBackground(new java.awt.Color(51, 255, 51));
        box17.setText("17");
        box17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box22.setBackground(new java.awt.Color(51, 255, 51));
        box22.setText("22");
        box22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box7.setBackground(new java.awt.Color(51, 255, 51));
        box7.setText("7");
        box7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box2.setBackground(new java.awt.Color(51, 255, 51));
        box2.setText("2");
        box2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box18.setBackground(new java.awt.Color(51, 255, 51));
        box18.setText("18");
        box18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box23.setBackground(new java.awt.Color(51, 255, 51));
        box23.setText("23");
        box23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box8.setBackground(new java.awt.Color(51, 255, 51));
        box8.setText("8");
        box8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box3.setBackground(new java.awt.Color(51, 255, 51));
        box3.setText("3");
        box3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box19.setBackground(new java.awt.Color(51, 255, 51));
        box19.setText("19");
        box19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box24.setBackground(new java.awt.Color(51, 255, 51));
        box24.setText("24");
        box24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box9.setBackground(new java.awt.Color(51, 255, 51));
        box9.setText("9");
        box9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box4.setBackground(new java.awt.Color(51, 255, 51));
        box4.setText("4");
        box4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box20.setBackground(new java.awt.Color(51, 255, 51));
        box20.setText("20");
        box20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box25.setBackground(new java.awt.Color(51, 255, 51));
        box25.setText("25");
        box25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box10.setBackground(new java.awt.Color(51, 255, 51));
        box10.setText("10");
        box10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box5.setBackground(new java.awt.Color(51, 255, 51));
        box5.setText("5");
        box5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box26.setBackground(new java.awt.Color(51, 255, 51));
        box26.setText("26");
        box26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box27.setBackground(new java.awt.Color(51, 255, 51));
        box27.setText("27");
        box27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box28.setBackground(new java.awt.Color(51, 255, 51));
        box28.setText("28");
        box28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        box29.setBackground(new java.awt.Color(51, 255, 51));
        box29.setText("29");
        box29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        box29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box29ActionPerformed(evt);
            }
        });

        box30.setBackground(new java.awt.Color(51, 255, 51));
        box30.setText("30");
        box30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnFinalizarCompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFinalizarCompra.setText("Finalizar compra");
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Horário:");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNome.setEnabled(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txthorario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txthorario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txthorario.setEnabled(false);
        txthorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthorarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txthorario, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(box11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(box12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(box16, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(box27, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box17, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(box18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(box13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(box19, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(box20, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(box5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(box7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(box8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(box9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(box10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(box26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box21, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(box28, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(box29, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(box30, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(box22, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(box23, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(box24, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(box25, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(btnFinalizarCompra)))
                .addGap(0, 125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txthorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box2)
                    .addComponent(box1)
                    .addComponent(box3)
                    .addComponent(box4)
                    .addComponent(box5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box6)
                    .addComponent(box7)
                    .addComponent(box8)
                    .addComponent(box9)
                    .addComponent(box10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box11)
                    .addComponent(box12)
                    .addComponent(box13)
                    .addComponent(box14)
                    .addComponent(box15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box16)
                    .addComponent(box17)
                    .addComponent(box18)
                    .addComponent(box19)
                    .addComponent(box20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box21)
                    .addComponent(box22)
                    .addComponent(box23)
                    .addComponent(box24)
                    .addComponent(box25))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box26)
                    .addComponent(box27)
                    .addComponent(box28)
                    .addComponent(box29)
                    .addComponent(box30))
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarCompra)
                .addGap(59, 59, 59))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void box29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box29ActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        try {
            // TODO add your handling code here:
            EscolherSessao es = new EscolherSessao();
            es.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(CompraIngresso.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txthorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorarioActionPerformed

    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
        // TODO add your handling code here:
        ArrayList<JCheckBox> box = this.retornarArray();
        
        for(JCheckBox checkbox: box) {
            if(checkbox.isSelected() && checkbox.isEnabled()) {
                IngressoDAO dao = new IngressoDAO();
                Ingresso i = new Ingresso();
                
                LoginCliente lc = new LoginCliente();
                Cliente c = lc.clienteLogado();
                
                EscolherSessao es = null;
                
                int index = box.indexOf(checkbox);
                try {
                    es = new EscolherSessao();
                } catch (SQLException ex) {
                    Logger.getLogger(CompraIngresso.class.getName()).log(Level.SEVERE, null, ex);
                }
                Sessao s = es.retornarSessao();
                i.setIdCliente(c.getId());
                i.setIdSessao(s.getId());
                i.setLugar(index);
                try {
                   dao.inserirIngresso(i);
                } catch (SQLException ex) {
                    Logger.getLogger(CompraIngresso.class.getName()).log(Level.SEVERE, null, ex);
                }
            }   
        }
        JOptionPane.showMessageDialog(this, "Compra realizada com sucesso!");
        this.dispose();
        try {
            EscolherFilme ef = new EscolherFilme();
            ef.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(CompraIngresso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFinalizarCompraActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box1ActionPerformed

    public void preencherCampo() throws SQLException{
        EscolherSessao es = new EscolherSessao();
        
        Sessao s = es.retornarSessao();
        txthorario.setText(s.getHorario());
        
        EscolherFilme ef = new EscolherFilme();
        
        Filme f = ef.filmeEscolhido();
        txtNome.setText(f.getNome());
                
    }
    
    public ArrayList<JCheckBox> retornarArray() {
        ArrayList<JCheckBox> box = new ArrayList();
        
        box.add(box1);
        box.add(box2);
        box.add(box3);
        box.add(box4);
        box.add(box5);
        box.add(box6);
        box.add(box7);
        box.add(box6);
        box.add(box8);
        box.add(box9);
        box.add(box10);
        box.add(box11);
        box.add(box12);
        box.add(box13);
        box.add(box14);
        box.add(box15);
        box.add(box16);
        box.add(box17);
        box.add(box18);
        box.add(box19);
        box.add(box20);
        box.add(box21);
        box.add(box22);
        box.add(box23);
        box.add(box24);
        box.add(box25);
        box.add(box26);
        box.add(box27);
        box.add(box28);
        box.add(box29);
        box.add(box30);
        
        return box;
    }
    
    public void recuperarIngressosVendidos() throws SQLException{
        IngressoDAO dao = new IngressoDAO();
        
        EscolherSessao es = new EscolherSessao();
        Sessao s = es.retornarSessao();
        
        ArrayList<Ingresso> ingressos = dao.procurarPorSessao(s.getId());
        
        
        ArrayList<JCheckBox> box = this.retornarArray();
               
        
        if(ingressos.size()>0){
        
            for(Ingresso i: ingressos){
                int lugar = i.getLugar();
                
               JCheckBox checkbox = box.get(lugar);
               checkbox.setSelected(true);
               checkbox.setEnabled(false);
               checkbox.setBackground(Color.RED);           
            }
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CompraIngresso().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CompraIngresso.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox box1;
    private javax.swing.JCheckBox box10;
    private javax.swing.JCheckBox box11;
    private javax.swing.JCheckBox box12;
    private javax.swing.JCheckBox box13;
    private javax.swing.JCheckBox box14;
    private javax.swing.JCheckBox box15;
    private javax.swing.JCheckBox box16;
    private javax.swing.JCheckBox box17;
    private javax.swing.JCheckBox box18;
    private javax.swing.JCheckBox box19;
    private javax.swing.JCheckBox box2;
    private javax.swing.JCheckBox box20;
    private javax.swing.JCheckBox box21;
    private javax.swing.JCheckBox box22;
    private javax.swing.JCheckBox box23;
    private javax.swing.JCheckBox box24;
    private javax.swing.JCheckBox box25;
    private javax.swing.JCheckBox box26;
    private javax.swing.JCheckBox box27;
    private javax.swing.JCheckBox box28;
    private javax.swing.JCheckBox box29;
    private javax.swing.JCheckBox box3;
    private javax.swing.JCheckBox box30;
    private javax.swing.JCheckBox box4;
    private javax.swing.JCheckBox box5;
    private javax.swing.JCheckBox box6;
    private javax.swing.JCheckBox box7;
    private javax.swing.JCheckBox box8;
    private javax.swing.JCheckBox box9;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txthorario;
    // End of variables declaration//GEN-END:variables
}
