package br.com.cinejov.views;

import br.com.cinejov.DAOs.SalaDAO;
import br.com.cinejov.DAOs.SessaoDAO;
import br.com.cinejov.entities.Filme;
import br.com.cinejov.entities.Sala;
import br.com.cinejov.entities.Sessao;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Otavio
 */
public class EscolherSessao extends javax.swing.JFrame {
    private static Sessao sessao;
    /**
     * Creates new form MenuCliente
     */
    public EscolherSessao() throws SQLException {
        initComponents();
        this.preencherLista();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        listaSessao = new javax.swing.JComboBox<>();
        btnEscolher = new javax.swing.JButton();
        txtSala = new javax.swing.JTextField();
        txtFilme = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Escolha sua sessão");

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVoltar.setText("voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        listaSessao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaSessaoActionPerformed(evt);
            }
        });

        btnEscolher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEscolher.setText("Escolher sessão");
        btnEscolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolherActionPerformed(evt);
            }
        });

        txtSala.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSala.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSala.setEnabled(false);
        txtSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaActionPerformed(evt);
            }
        });

        txtFilme.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFilme.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFilme.setEnabled(false);
        txtFilme.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Filme:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Sala:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Horário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(151, 151, 151)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(listaSessao, 0, 330, Short.MAX_VALUE)
                        .addComponent(btnEscolher, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFilme)
                        .addComponent(txtSala)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnVoltar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEscolher)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolherActionPerformed
        // TODO add your handling code here:
        SessaoDAO dao = new SessaoDAO();
        
        String horario = (String) listaSessao.getSelectedItem();
        String sala = txtSala.getText();
        
        EscolherFilme ef = null;
        try {
            ef = new EscolherFilme();
        } catch (SQLException ex) {
            Logger.getLogger(EscolherSessao.class.getName()).log(Level.SEVERE, null, ex);
        }
        Filme f = ef.filmeEscolhido();
        
        SalaDAO sdao = new SalaDAO();
        Sala s = null;
        try {
            s = sdao.procurarNome(sala);
            this.sessao = dao.procurarSessao(s.getId(), f.getId(), horario);
            CompraIngresso i = new CompraIngresso();
            this.dispose();
            i.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(EscolherSessao.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btnEscolherActionPerformed
    
    public Sessao retornarSessao(){
        return this.sessao;
    }
    
    public void preencherLista() throws SQLException{
        
             
        EscolherFilme ef = new EscolherFilme();
        Filme f =ef.filmeEscolhido();
        
        txtFilme.setText(f.getNome());
        
        SessaoDAO dao = new SessaoDAO();
        
        ArrayList<Sessao> sessoes = dao.procurarPorFilme(f.getId());
        
        for(Sessao s: sessoes){
            this.listaSessao.addItem(s.getHorario());
        }
    }
    
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
         EscolherFilme  ef = null;
        try {
            ef = new EscolherFilme();
        } catch (SQLException ex) {
            Logger.getLogger(EscolherSessao.class.getName()).log(Level.SEVERE, null, ex);
        }
         ef.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaActionPerformed

    private void listaSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaSessaoActionPerformed
        // TODO add your handling code here: 
        SessaoDAO dao = new SessaoDAO();
        
        String horario = (String) listaSessao.getSelectedItem();   
        
        try {
            SalaDAO sdao = new SalaDAO();
             
            EscolherFilme ef = new EscolherFilme();
            
            Filme f = ef.filmeEscolhido();
            
            Sessao s = dao.procurarUmaSessao(f.getId(), horario);
            
            Sala sl = sdao.procurarPorID(s.getIdSala());
               
            txtSala.setText(sl.getNome());
            txtFilme.setText(f.getNome());
            
        } catch (SQLException ex) {
            Logger.getLogger(EscolherSessao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listaSessaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolherSessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolherSessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolherSessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolherSessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EscolherSessao().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(EscolherSessao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscolher;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> listaSessao;
    private javax.swing.JTextField txtFilme;
    private javax.swing.JTextField txtSala;
    // End of variables declaration//GEN-END:variables
}
